name: Send Discord Gitlog Webhook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Content to GitHub Runner
        uses: actions/checkout@v2 # checkout to github runner

      - name: Send Gitlog to Discord Webhook URL Secret
        env:
          ENV_GITLOG_URL: ${{ secrets.GITLOG_URL }}
          job_status: ${{ job.status }}
        run: |
          messagearray=($(curl -i -s https://www.google.com/ | awk 'NR==1'))
          # this next line removes nasty characters that give json errors (keeps only letters, numbers SPACE and -)
          message=`echo ${messagearray[@]} | sed 's/[^0-9A-Za-z -]*//g'`;
          sendcontent='{"username": "Test", "content": "'"$job_status"'"}'
          curl -H "Content-Type: application/json" -d "$sendcontent" "$ENV_GITLOG_URL"